// // tailwind.config.js
// module.exports = {
//   darkMode: "class",
//   theme: {
//     extend: {
//       colors: {
//         "secondary-fixed-dim": "#ffb4a8",
//         "on-primary-container": "#858384",
//         "surface": "#fbf9f4",
//         "inverse-on-surface": "#f2f1ec",
//         "secondary-container": "#ff5c47",
//         "inverse-primary": "#c8c6c7",
//         "primary-fixed": "#e5e2e3",
//         "outline": "#76777b",
//         "on-tertiary-fixed": "#271900",
//         "secondary": "#b52619",
//         "inverse-surface": "#30312e",
//         "on-surface-variant": "#46474a",
//         "on-error": "#ffffff",
//         "tertiary-container": "#271900",
//         "on-secondary": "#ffffff",
//         "error-container": "#ffdad6",
//         "on-tertiary-fixed-variant": "#5d4200",
//         "surface-dim": "#dbdad5",
//         "primary-container": "#1b1b1c",
//         "surface-variant": "#e4e2dd",
//         "surface-tint": "#5f5e5f",
//         "surface-bright": "#fbf9f4",
//         "primary-fixed-dim": "#c8c6c7",
//         "primary": "#000000",
//         "tertiary": "#000000",
//         "surface-container-high": "#eae8e3",
//         "on-secondary-fixed-variant": "#920703",
//         "surface-container": "#f0eee9",
//         "on-primary-fixed": "#1b1b1c",
//         "on-primary": "#ffffff",
//         "surface-container-low": "#f5f3ee",
//         "on-tertiary": "#ffffff",
//         "on-background": "#1b1c19",
//         "on-secondary-fixed": "#410000",
//         "background": "#fbf9f4",
//         "tertiary-fixed-dim": "#f7bd48",
//         "on-error-container": "#93000a",
//         "error": "#ba1a1a",
//         "outline-variant": "#c7c6ca",
//         "on-secondary-container": "#610000",
//         "surface-container-highest": "#e4e2dd",
//         "on-primary-fixed-variant": "#474647",
//         "surface-container-lowest": "#ffffff",
//         "on-tertiary-container": "#ab7c00",
//         "on-surface": "#1b1c19",
//         "secondary-fixed": "#ffdad4",
//         "tertiary-fixed": "#ffdea6"
//       },
//       borderRadius: {
//         DEFAULT: "0.125rem",
//         lg: "0.25rem",
//         xl: "0.5rem",
//         full: "0.75rem"
//       },
//       spacing: {
//         unit: "8px",
//         marginMobile: "16px",
//         gutter: "24px",
//         sectionGap: "80px",
//         containerMax: "1280px",
//         marginDesktop: "64px"
//       },
//       fontFamily: {
//         displayLg: ["Playfair Display"],
//         labelMd: ["Manrope"],
//         headlineLg: ["Playfair Display"],
//         bodyLg: ["Manrope"],
//         bodyMd: ["Manrope"],
//         caption: ["Manrope"],
//         headlineMd: ["Playfair Display"]
//       },
//       fontSize: {
//         labelMd: ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
//         headlineLg: ["40px", { lineHeight: "48px", fontWeight: "600" }],
//         displayLg: ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "700" }],
//         bodyLg: ["18px", { lineHeight: "28px", fontWeight: "400" }],
//         bodyMd: ["16px", { lineHeight: "24px", fontWeight: "400" }],
//         caption: ["13px", { lineHeight: "18px", fontWeight: "400" }],
//         headlineMd: ["24px", { lineHeight: "32px", fontWeight: "600" }]
//       }
//     },
//   },
// }